// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnmawoemrdpgcmvooxsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxubWF3b2VtcmRwZ2Ntdm9veHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MjMxMDQsImV4cCI6MjA3NDI5OTEwNH0.qQh7lHwUWmhBBKqbG0Z5jYtEF1jDm8-izvFSeb78ZfM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});